"""Initial migration

Revision ID: 95876ce133c4
Revises: 
Create Date: 2026-01-16 02:41:52.750164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95876ce133c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('imagen_url', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('rif', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('persona_contacto', sa.String(length=100), nullable=True),
    sa.Column('tiempo_entrega_dias', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rif')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('tipo_usuario', sa.String(length=20), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('calificacion', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('combo_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_compra', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['combo_id'], ['combos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_pedido', sa.DateTime(), nullable=True),
    sa.Column('fecha_entrega_esperada', sa.DateTime(), nullable=True),
    sa.Column('fecha_entrega_real', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_compra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unidad_medida', sa.String(length=20), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combo_productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('combo_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['combo_id'], ['combos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_pedidos_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_proveedor.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('cantidad_minima', sa.Integer(), nullable=True),
    sa.Column('ultima_entrada', sa.DateTime(), nullable=True),
    sa.Column('ultima_salida', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('metodo_pago', sa.String(length=20), nullable=False),
    sa.Column('numero_referencia', sa.String(length=50), nullable=False),
    sa.Column('banco_origen', sa.String(length=100), nullable=True),
    sa.Column('telefono_pago', sa.String(length=20), nullable=True),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('verificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_verificacion', sa.DateTime(), nullable=True),
    sa.Column('notas_verificacion', sa.Text(), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], ),
    sa.ForeignKeyConstraint(['verificado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retiros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('numero_retiro', sa.String(length=20), nullable=False),
    sa.Column('numero_cola', sa.Integer(), nullable=False),
    sa.Column('fecha_retiro_programada', sa.DateTime(), nullable=False),
    sa.Column('fecha_retiro_real', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('tipo_cola', sa.String(length=20), nullable=True),
    sa.Column('atendido_por', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atendido_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_retiro')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retiros')
    op.drop_table('pagos')
    op.drop_table('inventario')
    op.drop_table('detalle_pedidos_proveedor')
    op.drop_table('combo_productos')
    op.drop_table('productos')
    op.drop_table('pedidos_proveedor')
    op.drop_table('compras')
    op.drop_table('comentarios')
    op.drop_table('usuarios')
    op.drop_table('proveedores')
    op.drop_table('combos')
    # ### end Alembic commands ###
